# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e07c8746a59fa751805652ba73ad1ec9a7776a27bf84853c83f6f2474c943ff61f33c5977c8860d6871ce3d5c62233f66dcf3a31f4d868b4ab8dc2f5cce0a47

test:
  secret_key_base: 312296910b2d0b9ac2c3dd5c0493dfcda394556567110b807c60f752e38daba29336a2b0372687163703a6947d070ea341234152065e2e6b32e59bb8e989c84b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
